import {NextResponse} from 'next/server';
import {session,canRead,canWrite} from '@/lib/auth';
import {SCHEMA,type TableName,type RecordRow} from '@/lib/schema';
import {getRows,append,update,audit} from '@/lib/sheets';
import {z} from 'zod';
function valid(t:string):t is TableName{return Object.prototype.hasOwnProperty.call(SCHEMA,t)}
const invalid=(error:string,status=400)=>NextResponse.json({error},{status});
export async function GET(_req:Request,ctx:{params:Promise<{table:string}>}){const user=await session();if(!user)return invalid('Unauthorized',401);const {table}=await ctx.params;if(!valid(table))return invalid('Unknown module',404);try{const rows=await getRows(table);return NextResponse.json({rows:rows.filter(r=>canRead(user,table,r)),columns:SCHEMA[table]})}catch(e){console.error(e);return invalid('Unable to load Google Sheets data',502)}}
export async function POST(req:Request,ctx:{params:Promise<{table:string}>}){const user=await session();if(!user)return invalid('Unauthorized',401);const {table}=await ctx.params;if(!valid(table)||['Audit_Log','Settings','Users'].includes(table))return invalid('Module unavailable',403);try{const payload=z.record(z.string(),z.union([z.string(),z.number(),z.boolean(),z.null()])).parse(await req.json());const allowed=new Set<string>(SCHEMA[table]);const clean:RecordRow={};for(const [k,v] of Object.entries(payload)){if(allowed.has(k)&&!['id','created_at','updated_at','created_by','owner_email'].includes(k))clean[k]=String(v??'')};const id=String(payload.id||'');let row;if(id){const existing=(await getRows(table)).find(r=>r.id===id);if(!existing)return invalid('Record not found',404);if(!canWrite(user,table,existing)||!canWrite(user,table,{...existing,...clean}))return invalid('Forbidden',403);row=await update(table,id,clean)}else{if(SCHEMA[table].includes('created_by' as never))clean.created_by=user.email;if(SCHEMA[table].includes('owner_email' as never))clean.owner_email=user.email;if(!canWrite(user,table,clean))return invalid('Forbidden',403);row=await append(table,clean)}await audit(user.email,id?'UPDATE':'CREATE',table,row.id);return NextResponse.json({record:row})}catch(e){console.error(e);return invalid('Unable to save record; check sheet access and fields',502)}}
