export const SCHEMA = {
  "Settings": [
    "key",
    "value",
    "updated_at"
  ],
  "MD_Profiles": [
    "id",
    "full_name",
    "designation",
    "official_email",
    "official_phone",
    "photo_url",
    "bio",
    "status",
    "created_at",
    "updated_at"
  ],
  "MD_Tenures": [
    "id",
    "md_id",
    "start_date",
    "end_date",
    "status",
    "notes",
    "created_at",
    "updated_at"
  ],
  "Departments": [
    "id",
    "name",
    "parent_department_id",
    "head_person_id",
    "description",
    "active",
    "created_at",
    "updated_at"
  ],
  "People": [
    "id",
    "full_name",
    "designation",
    "department_id",
    "email",
    "phone",
    "category",
    "reporting_person_id",
    "notes",
    "active",
    "created_at",
    "updated_at"
  ],
  "Organizations": [
    "id",
    "name",
    "organization_type",
    "sector",
    "website",
    "contact_email",
    "contact_phone",
    "address",
    "notes",
    "created_at",
    "updated_at"
  ],
  "Affiliations": [
    "id",
    "person_id",
    "organization_id",
    "designation",
    "from_date",
    "to_date",
    "created_at",
    "updated_at"
  ],
  "MD_Team": [
    "id",
    "person_id",
    "md_tenure_id",
    "role",
    "responsibility",
    "status",
    "created_at",
    "updated_at"
  ],
  "Meetings": [
    "id",
    "title",
    "start_at",
    "end_at",
    "venue",
    "type",
    "agenda",
    "notes",
    "status",
    "md_tenure_id",
    "confidentiality",
    "created_by",
    "created_at",
    "updated_at"
  ],
  "Meeting_People": [
    "id",
    "meeting_id",
    "person_id",
    "role",
    "created_at"
  ],
  "Meeting_Organizations": [
    "id",
    "meeting_id",
    "organization_id",
    "created_at"
  ],
  "Visitors": [
    "id",
    "person_id",
    "organization_id",
    "purpose",
    "appointment_at",
    "arrival_at",
    "departure_at",
    "host_person_id",
    "meeting_id",
    "status",
    "notes",
    "confidentiality",
    "created_by",
    "created_at",
    "updated_at"
  ],
  "Calendar": [
    "id",
    "title",
    "start_at",
    "end_at",
    "event_type",
    "meeting_id",
    "visitor_id",
    "md_tenure_id",
    "description",
    "confidentiality",
    "created_by",
    "created_at",
    "updated_at"
  ],
  "Tasks": [
    "id",
    "title",
    "description",
    "assigned_person_id",
    "source_type",
    "source_id",
    "priority",
    "deadline",
    "status",
    "progress",
    "remarks",
    "md_tenure_id",
    "confidentiality",
    "created_by",
    "created_at",
    "updated_at"
  ],
  "Decisions": [
    "id",
    "subject",
    "decision_text",
    "meeting_id",
    "responsible_person_id",
    "deadline",
    "status",
    "md_tenure_id",
    "confidentiality",
    "created_by",
    "created_at",
    "updated_at"
  ],
  "Notes": [
    "id",
    "title",
    "body",
    "related_type",
    "related_id",
    "owner_email",
    "md_tenure_id",
    "confidentiality",
    "created_at",
    "updated_at"
  ],
  "Follow_Ups": [
    "id",
    "subject",
    "related_type",
    "related_id",
    "responsible_person_id",
    "due_date",
    "next_action",
    "status",
    "created_by",
    "created_at",
    "updated_at"
  ],
  "Projects": [
    "id",
    "name",
    "department_id",
    "nodal_person_id",
    "status",
    "priority",
    "start_date",
    "target_date",
    "description",
    "md_tenure_id",
    "created_at",
    "updated_at"
  ],
  "Important_Matters": [
    "id",
    "title",
    "background",
    "department_id",
    "responsible_person_id",
    "next_action",
    "deadline",
    "status",
    "priority",
    "confidentiality",
    "md_tenure_id",
    "created_at",
    "updated_at"
  ],
  "Documents": [
    "id",
    "title",
    "drive_file_id",
    "mime_type",
    "related_type",
    "related_id",
    "version",
    "confidentiality",
    "uploaded_by",
    "created_at",
    "updated_at"
  ],
  "Correspondence": [
    "id",
    "subject",
    "sender",
    "recipient",
    "reference_number",
    "received_at",
    "due_date",
    "status",
    "related_type",
    "related_id",
    "confidentiality",
    "created_at",
    "updated_at"
  ],
  "Reminders": [
    "id",
    "title",
    "due_at",
    "related_type",
    "related_id",
    "assigned_person_id",
    "status",
    "created_at",
    "updated_at"
  ],
  "Notifications": [
    "id",
    "user_email",
    "title",
    "message",
    "read_at",
    "related_type",
    "related_id",
    "created_at"
  ],
  "Knowledge": [
    "id",
    "title",
    "body",
    "source_type",
    "source_id",
    "classification",
    "created_at",
    "updated_at"
  ],
  "Record_Links": [
    "id",
    "from_type",
    "from_id",
    "to_type",
    "to_id",
    "relationship",
    "created_at"
  ],
  "Audit_Log": [
    "id",
    "actor",
    "action",
    "table",
    "record_id",
    "details",
    "at"
  ]
} as const;
export type TableName = keyof typeof SCHEMA;
export const SYSTEM_TABLES = ["Settings", "Audit_Log", "Users"] as const;
export const MODULES = Object.keys(SCHEMA).filter((x)=> ![...SYSTEM_TABLES].includes(x as never)) as TableName[];
export type RecordRow = Record<string,string>;
export const TITLES: Partial<Record<TableName,string>> = { MD_Profiles:"MD Profiles", MD_Tenures:"MD Tenures", MD_Team:"MD Team", Meeting_People:"Meeting Participants", Meeting_Organizations:"Meeting Organizations", Follow_Ups:"Follow Ups", Important_Matters:"Important Matters", Record_Links:"Record Links" };
export const titleFor = (name:string) => TITLES[name as TableName] || name.replaceAll("_", " ");
