import 'server-only';
import {google} from 'googleapis';
import {randomUUID} from 'crypto';
import {SCHEMA, type TableName, type RecordRow} from './schema';
const spreadsheetId=()=>{if(!process.env.GOOGLE_SPREADSHEET_ID)throw Error('Missing GOOGLE_SPREADSHEET_ID');return process.env.GOOGLE_SPREADSHEET_ID};
function sheets(){const client=new google.auth.JWT({email:process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key:process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,'\n'),scopes:['https://www.googleapis.com/auth/spreadsheets']});return google.sheets({version:'v4',auth:client})}
const quote=(table:string)=>`'${table}'`;
export async function getRows(table:TableName):Promise<RecordRow[]>{const keys=SCHEMA[table] as readonly string[];const res=await sheets().spreadsheets.values.get({spreadsheetId:spreadsheetId(),range:`${quote(table)}!A:AZ`});const rows=(res.data.values||[]) as string[][];if(!rows.length)throw Error(`Missing sheet or headers: ${table}`);if(keys.some((k,i)=>rows[0][i]!==k))throw Error(`Column mismatch in ${table}. Use provided template.`);return rows.slice(1).filter(r=>r[0]).map(r=>Object.fromEntries(keys.map((k,i)=>[k,String(r[i]??'')])))}
export async function append(table:TableName,record:RecordRow){const keys=SCHEMA[table] as readonly string[];const now=new Date().toISOString();const r={...record,id:randomUUID(),created_at:now,updated_at:now};await sheets().spreadsheets.values.append({spreadsheetId:spreadsheetId(),range:`${quote(table)}!A:${col(keys.length)}`,valueInputOption:'RAW',insertDataOption:'INSERT_ROWS',requestBody:{values:[keys.map(k=>r[k]??'')]}});return r}
function col(n:number){let out='';while(n){n--;out=String.fromCharCode(65+n%26)+out;n=Math.floor(n/26)}return out}
export async function update(table:TableName,id:string,patch:RecordRow){const keys=SCHEMA[table] as readonly string[];const rows=await getRows(table);const index=rows.findIndex(x=>x.id===id);if(index<0)throw Error('Record not found');const current=rows[index];const r={...current,...patch,id,created_at:current.created_at,updated_at:new Date().toISOString()};await sheets().spreadsheets.values.update({spreadsheetId:spreadsheetId(),range:`${quote(table)}!A${index+2}:${col(keys.length)}${index+2}`,valueInputOption:'RAW',requestBody:{values:[keys.map(k=>r[k]??'')]}});return r}
export async function audit(actor:string,action:string,table:string,recordId:string){try{await append('Audit_Log',{actor,action,table,record_id:recordId,at:new Date().toISOString()})}catch(e){console.error('Audit write failed',e);throw Error('Audit write failed; check configuration')}}
